# Задачи к Лекции 7

Дан файл "Anuran_Calls_(MFCCs).zip", в котором содержится обработка звуков издаваемых различными видами лягушек. В качестве признаков выступают мел-кепстральные коэффициенты __[MFCC](https://en.wikipedia.org/wiki/Mel-frequency_cepstrum)__

**Чтение данных**

In [3]:
%matplotlib inline
import zipfile
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

z = zipfile.ZipFile("../data/Anuran_Calls_(MFCCs).zip")
df = pd.read_csv(z.open("Frogs_MFCCs.csv"))

df.head()

MFCCs_ 1  MFCCs_ 2  MFCCs_ 3  MFCCs_ 4  MFCCs_ 5  MFCCs_ 6  MFCCs_ 7  \
0       1.0  0.152936 -0.105586  0.200722  0.317201  0.260764  0.100945   
1       1.0  0.171534 -0.098975  0.268425  0.338672  0.268353  0.060835   
2       1.0  0.152317 -0.082973  0.287128  0.276014  0.189867  0.008714   
3       1.0  0.224392  0.118985  0.329432  0.372088  0.361005  0.015501   
4       1.0  0.087817 -0.068345  0.306967  0.330923  0.249144  0.006884   

   MFCCs_ 8  MFCCs_ 9  MFCCs_10    ...     MFCCs_17  MFCCs_18  MFCCs_19  \
0 -0.150063 -0.171128  0.124676    ...    -0.108351 -0.077623 -0.009568   
1 -0.222475 -0.207693  0.170883    ...    -0.090974 -0.056510 -0.035303   
2 -0.242234 -0.219153  0.232538    ...    -0.050691 -0.023590 -0.066722   
3 -0.194347 -0.098181  0.270375    ...    -0.136009 -0.177037 -0.130498   
4 -0.265423 -0.172700  0.266434    ...    -0.048885 -0.053074 -0.088550   

   MFCCs_20  MFCCs_21  MFCCs_22           Family      Genus         Species  \
0  0.057684  0.118680  0.014038  Leptodactylidae  Adenomera  AdenomeraAndre   
1  0.020140  0.082263  0.029056  Leptodactylidae  Adenomera  AdenomeraAndre   
2 -0.025083  0.099108  0.077162  Leptodactylidae  Adenomera  AdenomeraAndre   
3 -0.054766 -0.018691  0.023954  Leptodactylidae  Adenomera  AdenomeraAndre   
4 -0.031346  0.108610  0.079244  Leptodactylidae  Adenomera  AdenomeraAndre   

   RecordID  
0         1  
1         1  
2         1  
3         1  
4         1  

[5 rows x 26 columns]

**Получение различной информации**

In [3]:
df.shape

(7195, 26)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7195 entries, 0 to 7194
Data columns (total 26 columns):
MFCCs_ 1    7195 non-null float64
MFCCs_ 2    7195 non-null float64
MFCCs_ 3    7195 non-null float64
MFCCs_ 4    7195 non-null float64
MFCCs_ 5    7195 non-null float64
MFCCs_ 6    7195 non-null float64
MFCCs_ 7    7195 non-null float64
MFCCs_ 8    7195 non-null float64
MFCCs_ 9    7195 non-null float64
MFCCs_10    7195 non-null float64
MFCCs_11    7195 non-null float64
MFCCs_12    7195 non-null float64
MFCCs_13    7195 non-null float64
MFCCs_14    7195 non-null float64
MFCCs_15    7195 non-null float64
MFCCs_16    7195 non-null float64
MFCCs_17    7195 non-null float64
MFCCs_18    7195 non-null float64
MFCCs_19    7195 non-null float64
MFCCs_20    7195 non-null float64
MFCCs_21    7195 non-null float64
MFCCs_22    7195 non-null float64
Family      7195 non-null object
Genus       7195 non-null object
Species     7195 non-null object
RecordID    7195 non-null int64
dtypes: float6

In [5]:
df.describe()

MFCCs_ 1     MFCCs_ 2     MFCCs_ 3     MFCCs_ 4     MFCCs_ 5  \
count  7195.000000  7195.000000  7195.000000  7195.000000  7195.000000   
mean      0.989885     0.323584     0.311224     0.445997     0.127046   
std       0.069016     0.218653     0.263527     0.160328     0.162722   
min      -0.251179    -0.673025    -0.436028    -0.472676    -0.636012   
25%       1.000000     0.165945     0.138445     0.336737     0.051717   
50%       1.000000     0.302184     0.274626     0.481463     0.161361   
75%       1.000000     0.466566     0.430695     0.559861     0.222592   
max       1.000000     1.000000     1.000000     1.000000     0.752246   

          MFCCs_ 6     MFCCs_ 7     MFCCs_ 8     MFCCs_ 9     MFCCs_10  ...  \
count  7195.000000  7195.000000  7195.000000  7195.000000  7195.000000  ...   
mean      0.097939    -0.001397    -0.000370     0.128213     0.055998  ...   
std       0.120412     0.171404     0.116302     0.179008     0.127099  ...   
min      -0.410417    -0.538982    -0.576506    -0.587313    -0.952266  ...   
25%       0.012581    -0.125737    -0.063109     0.004648    -0.001132  ...   
50%       0.072079    -0.052630     0.013265     0.189317     0.063478  ...   
75%       0.175957     0.085580     0.075108     0.265395     0.117725  ...   
max       0.964240     1.000000     0.551762     0.738033     0.522768  ...   

          MFCCs_14     MFCCs_15     MFCCs_16     MFCCs_17     MFCCs_18  \
count  7195.000000  7195.000000  7195.000000  7195.000000  7195.000000   
mean     -0.039244    -0.101748     0.042062     0.088680     0.007755   
std       0.152515     0.187618     0.119915     0.138055     0.084733   
min      -0.590380    -0.717156    -0.498675    -0.421480    -0.759322   
25%      -0.132980    -0.255929    -0.019549    -0.001764    -0.042122   
50%      -0.050715    -0.143259     0.041081     0.112769     0.011820   
75%       0.039157     0.017348     0.107046     0.201932     0.061889   
max       0.575749     0.668924     0.670700     0.681157     0.614064   

          MFCCs_19     MFCCs_20     MFCCs_21     MFCCs_22     RecordID  
count  7195.000000  7195.000000  7195.000000  7195.000000  7195.000000  
mean     -0.049474    -0.053244     0.037313     0.087567    25.220014  
std       0.082546     0.094181     0.079470     0.123442    13.214399  
min      -0.680745    -0.361649    -0.430812    -0.379304     1.000000  
25%      -0.106079    -0.120971    -0.017620     0.000533    15.000000  
50%      -0.052626    -0.055180     0.031274     0.105373    22.000000  
75%       0.006321     0.001342     0.089619     0.194819    37.000000  
max       0.574209     0.467831     0.389797     0.432207    60.000000  

[8 rows x 23 columns]

In [15]:
df["Family"].value_counts()

Leptodactylidae    4420
Hylidae            2165
Dendrobatidae       542
Bufonidae            68
Name: Family, dtype: int64

**1. Провести интервальную оценку среднего значения признака "MFCCs_ 2" с помощью бутстрапа с точностью 95%.**

In [8]:
# Your code here

def bootstrap(data):
    idx = np.random.randint(0, len(data), len(data))
    print(idx," idx ")
    return data[idx]


mfcc_2 = []
data = df["MFCCs_ 2"].values

for i in range(50):
    t = bootstrap(data)
    print(t," t ")
    mfcc_2.append(t.mean())



[1457 1403 1267 ... 5106 4859 6293]  idx 
[ 0.09668533  0.24228506  0.43637454 ...  0.64074202 -0.05320881
  0.52777351]  t 
[1346  530 4615 ... 6412  607  934]  idx 
[0.27942725 0.53586404 0.04405262 ... 0.13948183 0.51049156 0.33859423]  t 
[3168 2844 3236 ... 5242 6156 1427]  idx 
[0.0605801  0.53059672 0.13327333 ... 0.64879941 0.16988935 0.17111115]  t 
[1848 6142 4774 ... 3376 1321 5735]  idx 
[ 0.1429107   0.17060972 -0.01825479 ...  0.13574154  0.26314303
  0.47976263]  t 
[7122 4401 2025 ...  840 2192 5383]  idx 
[-0.02657984  0.12766656  0.28087928 ...  0.29775196  0.09904785
  0.61378062]  t 
[4969 4550 5946 ... 7180 5217 4021]  idx 
[ 0.38733088  0.04723418  0.07871814 ... -0.52859524  0.6426991
  0.4192161 ]  t 
[2362  182 5892 ... 4530 5604  518]  idx 
[0.08410484 0.39824816 0.49601293 ... 0.16559772 0.13456314 0.54954368]  t 
[ 249  401 2554 ... 1011 5945 4133]  idx 
[0.36914497 0.50352554 0.31022193 ... 0.24589573 0.14930503 0.36660802]  t 
[1824 3846 2919 ... 5945 3146

In [9]:
print(np.percentile(mfcc_2, [5.0, 95.0]))

[0.3193949  0.32834576]


**2. Построить лес случайных деревьев, для определения семейства Dendrobatidae. Вывести 5 самых важных признаков. Сравнить результат с логистической регрессией.**

In [14]:
df.iloc[:,0:22].head()

MFCCs_ 1  MFCCs_ 2  MFCCs_ 3  MFCCs_ 4  MFCCs_ 5  MFCCs_ 6  MFCCs_ 7  \
0       1.0  0.152936 -0.105586  0.200722  0.317201  0.260764  0.100945   
1       1.0  0.171534 -0.098975  0.268425  0.338672  0.268353  0.060835   
2       1.0  0.152317 -0.082973  0.287128  0.276014  0.189867  0.008714   
3       1.0  0.224392  0.118985  0.329432  0.372088  0.361005  0.015501   
4       1.0  0.087817 -0.068345  0.306967  0.330923  0.249144  0.006884   

   MFCCs_ 8  MFCCs_ 9  MFCCs_10    ...     MFCCs_13  MFCCs_14  MFCCs_15  \
0 -0.150063 -0.171128  0.124676    ...    -0.156436  0.082245  0.135752   
1 -0.222475 -0.207693  0.170883    ...    -0.254341  0.022786  0.163320   
2 -0.242234 -0.219153  0.232538    ...    -0.237384  0.050791  0.207338   
3 -0.194347 -0.098181  0.270375    ...    -0.317084 -0.011567  0.100413   
4 -0.265423 -0.172700  0.266434    ...    -0.298524  0.037439  0.219153   

   MFCCs_16  MFCCs_17  MFCCs_18  MFCCs_19  MFCCs_20  MFCCs_21  MFCCs_22  
0 -0.024017 -0.108351 -0.077623 -0.009568  0.057684  0.118680  0.014038  
1  0.012022 -0.090974 -0.056510 -0.035303  0.020140  0.082263  0.029056  
2  0.083536 -0.050691 -0.023590 -0.066722 -0.025083  0.099108  0.077162  
3 -0.050224 -0.136009 -0.177037 -0.130498 -0.054766 -0.018691  0.023954  
4  0.062837 -0.048885 -0.053074 -0.088550 -0.031346  0.108610  0.079244  

[5 rows x 22 columns]

In [17]:
t=(df['Family'] == 'Dendrobatidae').values

array([False, False, False, ..., False, False, False])

In [60]:
%time
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X=df.iloc[:,0:22]
y=t

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,
random_state=42)
forest = RandomForestClassifier(50,n_jobs=3)
forest.fit(X_train, y_train)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.48 µs


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=3,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [61]:

print(forest.feature_importances_)
forest.feature_importances_
imp=forest.feature_importances_

[0.00153504 0.04053414 0.11352554 0.0452983  0.07145721 0.0102497
 0.03518424 0.01430954 0.04796436 0.04756081 0.02291141 0.03922041
 0.04566145 0.05935759 0.06034743 0.06499222 0.12333662 0.02951196
 0.03300019 0.03141507 0.03944164 0.0231851 ]


In [62]:
s=np.sort(imp)
print(s)

[0.00153504 0.0102497  0.01430954 0.02291141 0.0231851  0.02951196
 0.03141507 0.03300019 0.03518424 0.03922041 0.03944164 0.04053414
 0.0452983  0.04566145 0.04756081 0.04796436 0.05935759 0.06034743
 0.06499222 0.07145721 0.11352554 0.12333662]


In [63]:
i=len(s)-1
while (i>(len(s)-6)):
    l=s[i]
    idx=np.where(imp==l)
    print(s[i],idx,df.columns[idx])
    
    i-=1

0.12333661999761032 (array([16]),) Index(['MFCCs_17'], dtype='object')
0.11352554321212524 (array([2]),) Index(['MFCCs_ 3'], dtype='object')
0.07145720942877927 (array([4]),) Index(['MFCCs_ 5'], dtype='object')
0.06499221950097049 (array([15]),) Index(['MFCCs_16'], dtype='object')
0.06034743127272548 (array([14]),) Index(['MFCCs_15'], dtype='object')


делала отбор признаков

In [66]:
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

prob = forest.predict_proba(X_test)
pred = forest.predict(X_test)

print("Acc = ", accuracy_score(y_test, pred))
print("F1 = ", f1_score(y_test, pred))
print("ROC AUC = ", roc_auc_score(y_test, prob[:, 1]))

Acc =  0.9966648137854364
F1 =  0.9774436090225563
ROC AUC =  0.9999801032860529


впечатляет

In [67]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X_train, y_train)

prob = logreg.predict_proba(X_test)
pred = logreg.predict(X_test)

print("Acc = ", accuracy_score(y_test, pred))
print("F1 = ", f1_score(y_test, pred))
print("ROC AUC = ", roc_auc_score(y_test, prob[:, 1]))

Acc =  0.9833240689271817
F1 =  0.88
ROC AUC =  0.9941503660995366


**3. Использовать бэггинг для обучения 100 логистических регрессий для определения семейства Dendrobatidae. Использовать RandomizedSearchCV для того, чтобы не перебирать все возможные комбинации параметров. Выбрать для RandomizedSearchCV - 20 итераций.**

In [85]:
from sklearn.ensemble import BaggingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV

parameters = {
    'max_features': [5, 10, 15],    # кол-во случайно отбираемых признаков
    'max_samples': [0.55, 0.75, 0.9], # процент выборки для обучения 
    'base_estimator__C': np.logspace(-4, 5, 10), # регуляризация
}


# Your code here

clf = BaggingClassifier(LogisticRegression(solver="liblinear"), 100)

rcv = RandomizedSearchCV(clf, parameters, n_iter=20, scoring="roc_auc", cv=2)

rcv.fit(X_train, y_train)


RandomizedSearchCV(cv=2, error_score='raise',
          estimator=BaggingClassifier(base_estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start..._estimators=100, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False),
          fit_params=None, iid=True, n_iter=20, n_jobs=1,
          param_distributions={'max_features': [5, 10, 15], 'max_samples': [0.55, 0.75, 0.9], 'base_estimator__C': array([1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03,
       1.e+04, 1.e+05])},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score='warn', scoring='roc_auc', verbose=0)

In [86]:
pred = rcv.predict(X_test)
print("Acc = ", accuracy_score(y_test, pred))

Acc =  0.9838799332962757


In [87]:
odin=LogisticRegression(solver="liblinear")
odin.fit(X_train, y_train)
pred = odin.predict(X_test)
print("Acc = ", accuracy_score(y_test, pred))

Acc =  0.9833240689271817


**(опционально) 4. Организовать стекинг моделей (любой из вариантов) для определения семейства Dendrobatidae. Для этого выбрать базовые модели и выбрать мета-модель (самостоятельно). Определить постепенным добавление, какие модели улучшают результат классификации, какие ухудшают.**

In [20]:
# A lot of code here